baseURL = '/'
languageCode = 'ru'
title = 'Название сайта'

disableKinds = ['taxonomy', 'term']
disableHugoGeneratorInject = true

[params]
city = 'Тольятти'
description = "Описание сайта"

[outputs]
home = ['html']

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
autoHeadingID = false

[build]
  writeStats = true
  
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'node_modules/bootstrap/scss'
    target = 'assets/scss'
  [[module.mounts]]
    source = 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js'
    target = 'assets/js/vendor/bootstrap.bundle.min.js'
