baseURL = '/'
languageCode = 'ru'
title = 'Название сайта'
description = "Описание сайта"

disableKinds = ['taxonomy', 'term']
disableHugoGeneratorInject = true

[params]
city = 'Тольятти'

[outputs]
home = ['html']

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[build]
noJSConfigInAssets = true
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'

[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'
